name: "Build"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    environment: 
      name: Testing
      url: https://github.com
    steps:
      - name: is_member
        uses: TheModdingInquisition/actions-team-membership@8e9d713e461f3dcc7202f75e293c1443ce1c926b
        with:
          team: 'moddedjanitors'
          token: ${{ secrets.TOKEN }}
      - if: ${{ steps.is_member.outputs.permitted == 'true' }}
        run: echo 'Yes'