name: "Build"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    environment: 
      name: Testing
      url: https://github.com
    steps:
      - id: is_member
        uses: TheModdingInquisition/actions-team-membership@50febd6ab60162a4928889be52f9517a63740f2c
        with:
          team: 'moddedjanitors'
          token: ${{ secrets.TOKEN }}
      - if: ${{ steps.is_member.outputs.permitted == 'true' }}
        run: echo 'Yes'
      - run: echo ${{ steps.is_member.outputs.teams }}