name: "Build"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    environment: 
      name: Testing
      url: https://github.com
    steps:
      - name: is_member
        uses: TheModdingInquisition/actions-team-membership@bb2f011e4ca39f929a09159c4ac25aa9982c6a17
        with:
          team: 'moddedjanitors'
          token: ${{ secrets.TOKEN }}
      - if: ${{ steps.is_member.outputs.permitted == 'true' }}
        run: echo 'Yes'
      - run: echo ${{ steps.is_member.outputs.teams }}