name: "Build"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: is_member
        uses: TheModdingInquisition/actions-team-membership@af0c319b8cf8a881a6fc6194f916aaad758589fe
        with:
          team: 'moddedjanitors'
      - if: ${{ steps.is_member.outputs.permitted == 'true' }}
        run: echo 'Yes'